name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      
      # Steps specific to Linux
      - name: Build with PyInstaller on Linux
        if: matrix.os == 'ubuntu-latest'
        run: pyinstaller main.spec
          
      # Steps specific to Windows
      - name: Build with PyInstaller on Windows
        if: matrix.os == 'windows-latest'
        run: pyinstaller main.spec
          
      # Steps specific to macOS
      - name: Build with PyInstaller on macOS
        if: matrix.os == 'macos-latest'
        run: pyinstaller main.spec
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-app
          path: dist/
